# define: fileserve::resource::directory
#
# This definition creates a directory
#
# Parameters:

define fileserve::resource::directory (
  $file_name               = $name,
  $path                    = $name, # (namevar) The path to the file to manage.  Must be fully...
  $content                 = undef, # The desired contents of a file, as a string...
  $force                   = undef, # Perform the file operation even if it will...
  $group                   = 'root', # Which group should own the file.  Argument can...
  $ignore                  = undef, # A parameter which omits action on files matching
  $links                   = undef, # How to handle links during file actions.  During
  $mode                    = '0755',# The desired permissions mode for the file, in...
  $owner                   = 'root', # The user to whom the file should belong....
  $purge                   = false, # Whether unmanaged files should be purged. This...
  $recurse                 = undef, # Whether to recursively manage the _contents_ of...
  $recurselimit            = undef, # How far Puppet should descend into...
  $show_diff               = undef, # Whether to display differences when the file...
  $source                  = undef, # A source file, which will be copied into place...
  $source_permissions      = undef, # Whether (and how) Puppet should copy owner...
  $sourceselect            = 'first', # Whether to copy all valid sources, or just the...
  $target                  = undef, # The target for creating a link.  Currently...
  $validate_cmd            = undef, # A command for validating the file's syntax...
  $validate_replacement    = undef, # The replacement string in a `validate_cmd` that...
){

    file { $file_name:
      path                    => $path,
      ensure                  => 'directory',
      group                   => $group,
      mode                    => $mode,
      owner                   => $owner,
      source                  => $source,
      sourceselect            => $sourceselect,
      recurse                 => true,
      purge                   => $purge,
    }
}
