# define: fileserve::resource::file
#
# This definition creates a file
#
# Parameters:,
define fileserve::resource::file (
  $file_name               = $name,
  $path                    = $name, # (namevar) The path to the file to manage.  Must be fully...
  $ensure                  = 'present', # Whether the file should exist, and if so what...
  $backup                  = undef, # Whether (and how) file content should be backed...
  $checksum                = undef, # The checksum type to use when determining...
  $checksum_value          = undef, # The checksum of the source contents. Only md5...
  $content                 = undef, # The desired contents of a file, as a string...
  $ctime                   = undef, # A read-only state to check the file ctime. On...
  $force                   = undef, # Perform the file operation even if it will...
  $group                   = 'root', # Which group should own the file.  Argument can...
  $ignore                  = undef, # A parameter which omits action on files matching
  $links                   = undef, # How to handle links during file actions.  During
  $mode                    = '0644', # The desired permissions mode for the file, in...
  $mtime                   = undef, # A read-only state to check the file mtime. On...
  $owner                   = 'root', # The user to whom the file should belong....
  $provider                = undef, # The specific backend to use for this `file...
  $purge                   = undef, # Whether unmanaged files should be purged. This...
  $recurse                 = undef, # Whether to recursively manage the _contents_ of...
  $recurselimit            = undef, # How far Puppet should descend into...
  $replace                 = undef, # Whether to replace a file or symlink that...
  $show_diff               = undef, # Whether to display differences when the file...
  $source                  = undef, # A source file, which will be copied into place...
  $source_permissions      = undef, # Whether (and how) Puppet should copy owner...
  $sourceselect            = undef, # Whether to copy all valid sources, or just the...
  $target                  = undef, # The target for creating a link.  Currently...
  $type                    = undef, # A read-only state to check the file...
  $validate_cmd            = undef, # A command for validating the file's syntax...
  $validate_replacement    = undef, # The replacement string in a `validate_cmd` that...
){
    file { $file_name:
      path                    => $path,
      ensure                  => $ensure,
      content                 => $content,
      group                   => $group,
      mode                    => $mode,
      owner                   => $owner,
      source                  => $source,
    }
  }